config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'  
  resources :users
  resources :account_activations, only: [:edit]
  resources :microposts, only: [:create, :destroy]
  resources :users do
    member do
    get :following, :followers
    end
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  by <a href="https://github.com/Adhikram">Adhikram Maitra</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-dark">
	<div class="container-fluid d-flex justify-content-center"> 
		<a class="navbar-brand" href="#" id= "logo" >Sage's Corner</a>
			<ul class="navbar-nav  mb-2 mb-lg-0" id ="flat"> 
				<li class="nav-item">
					<li><%= link_to "Home", root_path ,class:"nav-link"%></li> 
        </li>
				<li class="nav-item">
					<li><%= link_to "Help", help_path ,class:"nav-link"%></li> 
        </li>
				<% if logged_in? %> 
					<li class="nav-item">
						<li><%= link_to "Users", users_path ,class:"nav-link" %></li>
					 </li>
					
					<li class="nav-item dropdown"> 
						<a class="nav-link dropdown-toggle" href="#"  data-toggle="dropdown" aria-haspopup="true">Dropdown</a> 
						<ul class="dropdown-menu bg-dark text-light"  x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 39px, 0px);" > 
							<li><%= link_to "Profile", current_user,class:"dropdown-item text-light" %></li> 
							<li class="divider"></li> 
							<li><%= link_to "Settings", edit_user_path(current_user) ,class:"dropdown-item  text-light" %></li>  
							<li class="divider"></li> 
							<li><%= link_to "Log out", logout_path, method: :delete ,class:"dropdown-item text-light"%> </li> 
						</ul> 
					</li> 
				<% else %> 
				<li class="nav-item">
					<li><%= link_to "Log in", login_path ,class:"nav-link" %></li> 
        </li>
				<% end %> 

			</ul> 
	</div> 
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= full_title(yield(:title)) %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all',
'data-turbolinkstrack': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinkstrack': 'reload' %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>
<%= yield %>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>